name: travel_hour
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.2.0+21

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  animated_bottom_navigation_bar: ^1.3.3
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.8
  dots_indicator: ^3.0.0
  easy_localization: ^3.0.2
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_storage: ^12.1.3
  firebase_in_app_messaging: ^0.8.0+4
  flare_flutter: ^3.0.2
  flutter_html: ^3.0.0-beta.2
  flutter_polyline_points: ^2.1.0
  geo: ^0.3.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  google_sign_in: ^6.2.1
  html_unescape: ^2.0.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  launch_review: ^3.0.1
  line_icons: ^2.0.3
  package_info: ^2.0.2
  provider: ^6.1.2
  share: ^2.0.4
  shared_preferences: ^2.3.2
  skeleton_text: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.3.0
  the_apple_sign_in: ^1.1.1
  fluttertoast: ^8.2.8
  flutter_facebook_auth: ^7.1.0
  flutter_web_browser: ^0.17.1
  google_mobile_ads: ^5.1.0
  pod_player: ^0.2.2
  app_settings: ^5.1.1
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  md2_tab_indicator:
    git:
      url: https://github.com/westdabestdb/md2_tab_indicator
  another_carousel_pro:
    git:
      url: https://github.com/iamnabink/another_carousel_pro
      ref: 6bd1b57
  hexcolor: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.3.0

flutter_icons:
  android: true  # Enable Android adaptive icons
  ios: true
  image_path: "assets/images/icon.png"  # Path to your custom icon
  adaptive_icon_background: "#FFBF00"  # Background color for adaptive icon on Android
  adaptive_icon_foreground: "assets/images/icon.png"  # Foreground icon for adaptive icon

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/flr/
    - assets/translations/
    - assets/images/conversational_guide_1.png
    - assets/images/conversational_guide_2.png
    - assets/images/conversational_guide_3.png
    - assets/images/emergency_hotline_1.png
    - assets/images/emergency_hotline_2.png
    - assets/images/transportation_1.png
    - assets/images/transportation_2.png
    - assets/images/transportation_3.png
    - assets/images/transportation_4.png  
    - assets/images/icon.png  # Your launcher icon

  fonts:

    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 500
        - asset: assets/fonts/Muli-Medium.ttf
          weight: 600
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 800

    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900

    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
