// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4X8his7j33WNGZ7aL-iM2KJC64vjTeQk',
    appId: '1:883051571925:web:9dd34f941b6a5b9975505c',
    messagingSenderId: '883051571925',
    projectId: 'surioao',
    authDomain: 'surioao.firebaseapp.com',
    storageBucket: 'surioao.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqbTQKpWQOVYVhwQShiy-0jdQC_kd1jD4',
    appId: '1:883051571925:android:fba3b93404a344f875505c',
    messagingSenderId: '883051571925',
    projectId: 'surioao',
    storageBucket: 'surioao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVTillsKXClU4Cu59mBPXAuwyZfZRUpl8',
    appId: '1:883051571925:ios:7f31255bb224977975505c',
    messagingSenderId: '883051571925',
    projectId: 'surioao',
    storageBucket: 'surioao.appspot.com',
    iosBundleId: 'suroiaotravelhourapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVTillsKXClU4Cu59mBPXAuwyZfZRUpl8',
    appId: '1:883051571925:ios:cee9747219b9774475505c',
    messagingSenderId: '883051571925',
    projectId: 'surioao',
    storageBucket: 'surioao.appspot.com',
    iosBundleId: 'suroiaotravelHour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4X8his7j33WNGZ7aL-iM2KJC64vjTeQk',
    appId: '1:883051571925:web:d5c4e261ea50059e75505c',
    messagingSenderId: '883051571925',
    projectId: 'surioao',
    authDomain: 'surioao.firebaseapp.com',
    storageBucket: 'surioao.appspot.com',
  );
}
